AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VPCCIDR:
    Description: VPC CIDR block
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Join ['', ["VPC-", !Ref "AWS::StackName"]]